# Site settings
name: 苑海亮博客
email: for.hailiang.yuan@gmail.com
author: Freud Kang
url: https://hailiangyuan.github.io/blog.github.io/
resume_site: https://hailiangyuan.github.io/blog/Resume.io/
github: https://hailiangyuan.github.io/blog.github.io/
baseurl: "/blog.github.io"
description: 生活的最大乐趣便是完成别人认为你不可能做到的事情！
meta_description: 苑海亮;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: Accomplish what others think you cannot do.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: hailiangyuan

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9


